spring:
  application:
    name: notification-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka
server:
  port: 8083