spring.application.name=productsrvc
server.port=8081
#server.port=${PORT:0}
#eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
#spring.datasource.username=postgres
#spring.datasource.password=postgres
# Habilita el procesamiento por lotes para inserciones y actualizaciones
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka