spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: productsrvc
              uri: lb://productsrvc
              predicates:
                - Path=/api/product-service/**
              filters:
                - StripPrefix=2
            - id: ordersrvc
              uri: lb://ordersrvc
              predicates:
                - Path=/api/order-service/**
              filters:
                - StripPrefix=2
            - id: paymentsrvc
              uri: lb://paymentsrvc
              predicates:
                - Path=/api/payment-service/**
              filters:
                - StripPrefix=2
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE